In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
a = torch.tensor([0.230685, 0.89133, 0.365109])
b = torch.tensor([[-2.48654, -0.866873, 0.890341, -0.854835, 0.125772], [0.342647, 1.28995, 2.57582, 0.328219, -1.72174], [-0.627516, 0.737613, 0.282489, -0.18954, 0.202373]])
a.matmul(b)

tensor([-0.4973,  1.2191,  2.6044,  0.0262, -1.4317])

In [14]:
c = torch.ones(3, 3)
c.matmul(c)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [11]:
d = torch.tensor([[1.0362e+08, 6.27859e+06, -4.50592e+06], [-2.90708e+08, -1.76147e+07, 1.26414e+07], [7.79498e+08, 4.72316e+07, -3.38964e+07], [-4.04768e+08, -2.45259e+07, 1.76013e+07], [6.14226e+07, 3.72174e+06, -2.67096e+06], [-1.97159e+08, -1.19464e+07, 8.57346e+06], [4.26222e+08, 2.58258e+07, -1.85342e+07], [2.61826e+08, 1.58647e+07, -1.13855e+07], [3.1201e+08, 1.89054e+07, -1.35677e+07], [3.30194e+08, 2.00072e+07, -1.43585e+07], [-1.88818e+08, -1.14409e+07, 8.21074e+06], [1.08967e+08, 6.60254e+06, -4.73841e+06], [-1.65565e+08, -1.0032e+07, 7.1996e+06], [-1.94375e+08, -1.17776e+07, 8.45239e+06], [6.52207e+08, 3.95188e+07, -2.83612e+07], [1.23289e+08, 7.47035e+06, -5.3612e+06]])
e = torch.tensor([[0.230685, -0.866873, 0.342647, -1.72174, -0.18954, 0.673161, -0.472415, 0.189262, 0.319197, -0.686457, 1.11783, 0.272488, -0.0830151, -0.0659093, 0.810348, -0.414134], [0.89133, 0.890341, 1.28995, -0.627516, 0.202373, -0.131711, 1.30916, -0.832299, 1.10598, 0.696329, -0.868199, -1.18842, -0.795619, -0.523787, 1.78561, -0.448247], [0.365109, -0.854835, 2.57582, 0.737613, 0.541478, -1.95011, 1.8935, 1.98107, -0.0434281, 1.86231, -1.41629, 1.24978, -0.169522, 0.418244, 1.13165, 1.07189], [-2.48654, 0.125772, 0.328219, 0.282489, -0.274135, 0.151625, 0.443215, -1.22573, 1.55543, 1.26298, -2.0383, -1.0397, -0.148639, -3.27348, -0.374892, 1.51381]])
f = d.matmul(e)
print(f)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x3 and 4x16)

In [54]:
v = torch.tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]], dtype=torch.float32)
c = torch.tensor([[2, 3, 4], [3, 4, 5], [4, 5, 6]], dtype=torch.float32)
v.matmul(c)

tensor([[20., 26., 32.],
        [29., 38., 47.],
        [38., 50., 62.]])

In [67]:
t = torch.tensor([[[0.230685, 0.89133, 0.365109], [-2.48654, -0.866873, 0.890341], [-0.854835, 0.125772, 0.342647]], [[1.28995, 2.57582, 0.328219], [-1.72174, -0.627516, 0.737613], [0.282489, -0.18954, 0.202373]], [[0.541478, -0.274135, 0.673161], [-0.131711, -1.95011, 0.151625], [-0.472415, 1.30916, 1.8935]]])
v = torch.tensor([[[0.443215, 0.189262, -0.832299], [1.98107, -1.22573, 0.319197], [1.10598, -0.0434281, 1.55543]]])
t.matmul(v)

tensor([[[ 2.2718, -1.0647,  0.6604],
         [-1.8347,  0.5533,  3.1777],
         [ 0.2492, -0.3308,  1.2846]],

        [[ 6.0376, -2.9274,  0.2591],
         [-1.1905,  0.4113,  2.3800],
         [-0.0265,  0.2770,  0.0192]],

        [[ 0.4414,  0.4093,  0.5089],
         [-3.7540,  2.3588, -0.2770],
         [ 4.4783, -1.7763,  3.7563]]])

In [114]:
t = torch.Tensor([0.230685, 0.89133, 0.365109])
v = t.softmax(0)
print(t)
print(v)

tensor([0.2307, 0.8913, 0.3651])
tensor([0.2451, 0.4745, 0.2804])


In [86]:
t = torch.Tensor([])
t.size()

torch.Size([0])