In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
a = torch.tensor([[1, 1], [1, 1], [1, 1]])
b = torch.tensor([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
b.matmul(a)

tensor([[3, 3],
        [3, 3],
        [3, 3]])

In [14]:
c = torch.ones(3, 3)
c.matmul(c)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [21]:
d = torch.tensor([[[1, 1], [1, 1], [1, 1]], [[1, 1], [1, 1], [1, 1]]])
e = torch.tensor([[1, 1, 1], [1, 1, 1]])
d.matmul(e)
print(d)

tensor([[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]])


In [54]:
v = torch.tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]], dtype=torch.float32)
c = torch.tensor([[2, 3, 4], [3, 4, 5], [4, 5, 6]], dtype=torch.float32)
v.matmul(c)

tensor([[20., 26., 32.],
        [29., 38., 47.],
        [38., 50., 62.]])

In [67]:
t = torch.tensor([[[0.230685, 0.89133, 0.365109], [-2.48654, -0.866873, 0.890341], [-0.854835, 0.125772, 0.342647]], [[1.28995, 2.57582, 0.328219], [-1.72174, -0.627516, 0.737613], [0.282489, -0.18954, 0.202373]], [[0.541478, -0.274135, 0.673161], [-0.131711, -1.95011, 0.151625], [-0.472415, 1.30916, 1.8935]]])
v = torch.tensor([[[0.443215, 0.189262, -0.832299], [1.98107, -1.22573, 0.319197], [1.10598, -0.0434281, 1.55543]]])
t.matmul(v)

tensor([[[ 2.2718, -1.0647,  0.6604],
         [-1.8347,  0.5533,  3.1777],
         [ 0.2492, -0.3308,  1.2846]],

        [[ 6.0376, -2.9274,  0.2591],
         [-1.1905,  0.4113,  2.3800],
         [-0.0265,  0.2770,  0.0192]],

        [[ 0.4414,  0.4093,  0.5089],
         [-3.7540,  2.3588, -0.2770],
         [ 4.4783, -1.7763,  3.7563]]])

In [114]:
t = torch.Tensor([0.230685, 0.89133, 0.365109])
v = t.softmax(0)
print(t)
print(v)

tensor([0.2307, 0.8913, 0.3651])
tensor([0.2451, 0.4745, 0.2804])


In [86]:
t = torch.Tensor([])
t.size()

torch.Size([0])